// ============================================================
//  雅思词伙 (Collocations) — 来源：《手把手教你雅思词伙 2.0》(顾家北)
//  用途：批改时「用词提升建议」+ 词伙参考弹窗
//  说明：词伙强调「话题相关、多词组合、自然搭配」，以下为按雅思常考话题整理的 authentic collocations
// ============================================================

var CIHUO = {
  "健康与家庭": [
    "affect their health", "afford basic necessities", "and for this reason", "balanced diet",
    "children from less well-off backgrounds", "children from poor homes", "dis-advantaged children", "easy access to medical services",
    "elderly care", "elderly people", "endanger health", "engage children",
    "family bond", "family life", "festive season", "folk songs",
    "form strong personal relationships", "gentle physical exercise", "harmful to health", "health cost",
    "health problems", "healthy eating", "heart diseases", "hit songs",
    "holiday season", "household goods", "improve health", "improve physical health",
    "incurable diseases", "invent new drugs", "medical aid", "medical equipment",
    "medical expenses", "medical research", "medical system", "mental wellbeing",
    "mild exercise", "misuse of drugs", "pest disease", "physical activity",
    "physical exercise", "pop songs", "practice medicine", "prevent the pest disease",
    "prone to health problem", "raise a family", "raise a family/start a family", "raise children",
    "reasonable price", "receive medical treatments", "see doctors", "stay healthy",
    "suffer from heart diseases", "suffer from poor health", "the company of family"
  ],
  "全球化与文化": [
    "art museums", "attract tourists", "body language", "celebrate festivals",
    "century-old heritage buildings architectural heritage", "cross-cultural understanding", "cultural attraction", "cultural attractions",
    "cultural diversity", "cultural heritage", "cultural identity", "cultural shocks",
    "cultural site", "customer satisfaction", "dominant languages", "economic globalisation",
    "enrich cultural lives", "exhibit artefacts", "fluent in the first language", "go overseas",
    "good customer services", "heritage building", "historic buildings", "immerse themselves in a foreign language",
    "improve language skills", "language skills", "less spoken language", "less spoken languages",
    "local tourist attractions", "master a foreign language", "master another language", "master this language",
    "pick up a language", "preserve language diversity", "preserve traditions", "protect languages",
    "tourism boom", "tourist attractions", "tourist destinations", "traditional values",
    "traditional ways of life", "use bad language", "vitally important"
  ],
  "其他话题": [
    "a connection to the past", "a decent meal", "a good harvest", "a good motivator",
    "a growing population", "a lack of sleep", "a lasting friendship", "a life-changing experience",
    "a long waiting list", "a means of communication", "a memorable experience", "a negative effect",
    "a poor village", "a possible option", "a primary cause", "a reliable source of information",
    "a sense of achievement", "a sense of responsibility", "a sign of respect", "a strict dress code",
    "a tight schedule", "a tight timetable", "absorb dirt and smoke", "absorb dust",
    "achieve a sense of independence", "achieve ambitions", "achieve fame", "achieve shared targets",
    "achieve success", "adapt to the local culture", "admire celebrities", "admission fees",
    "afford basic necessities", "afford home ownership", "air fares", "alternative methods",
    "among the most affected", "and explain why it was enjoyable", "architectural landmark", "architectural landmarks",
    "architectural treasure", "architectural treasures", "attain goals", "attend meetings",
    "attend meetings on time", "avoid misunderstandings", "awash with rubbish", "bad behaviour enter adulthood",
    "basic needs", "be amazed by", "be experienced in", "be exposed to",
    "be mitigated", "be overused", "be seen as", "behave selfishly",
    "behavioural problems", "believing that these products", "blowing out candles", "boil water",
    "boost brain activity", "bottled water", "brain development", "bring people together",
    "bring together", "build character", "build expertise", "build new roads",
    "build strength", "build up", "build up in the atmosphere", "burn calories",
    "buy gifts", "buy more than they need", "buy presents", "capture special moments",
    "car giants", "car ownership", "car pooling", "carry weapons",
    "charge admission fees", "charitable organisations", "charity groups", "check blogs",
    "check the timetable take a dip", "chemical fertilisers", "choose subjects", "circle of friends",
    "class activities", "clear forests", "clinical experience", "close friends",
    "collect information", "come of age", "come up with", "common interests",
    "compare products", "competitive advantages", "competitive advantages intense competition", "complete a project",
    "conscious of other people's interest", "construct facilities", "contaminated water", "continue studies",
    "core subjects", "cost reduction measures", "cover basic needs", "create exhaust fumes",
    "create new possibilities", "cultivate crops", "curb smoking", "deliver products",
    "depend on", "deprived areas", "design drills", "design quizzes",
    "designer clothes", "destroy the forest", "develop a lifelong friendship", "develop a sense of identity",
    "develop a strong relationship", "develop a talent", "develop qualities", "develop talents",
    "die out", "differ from culture to culture", "discover talents", "discrimination on the grounds of sex",
    "domestic responsibilities", "dress formally", "drive prestigious cars", "drive private cars",
    "driven by self-interest", "driving license", "drop litter", "dying needlessly",
    "earn a fortune", "earn salaries", "electrical equipment", "embark on a team project",
    "embark on another team project", "emulate idols", "encounter difficulties demonstrate determination", "encounter problems",
    "enter our food chain", "eve their creative potential", "experience difficult times", "experience difficulties",
    "experience the world", "extra-curricular activities", "extreme weather conditions", "face a high risk of extinction",
    "face challenges", "face challenges in", "face to face communication", "face-to-face communication",
    "fall ill", "feast for your eyes Cantonese food", "find contentment behind the times", "find enjoyment",
    "fire enthusiasm", "fit into the modern", "flowering plants", "focus on",
    "follow advice", "food prices", "food production", "food shortage",
    "forbid cheating", "forested areas", "form a good relationship", "free admission",
    "free entry", "free time", "friends of the opposite sex", "gM food",
    "gain an unfair advantage over", "gain emotional support", "gain support", "gather first-hand information",
    "gender Discrimination", "gender bias", "gender differences", "gender discrimination",
    "gender equality", "gender gap", "gender gap narrows", "genetic engineering",
    "get distracted", "get into debt", "give a helping hand", "give priority to",
    "go bankrupt", "go bust", "go for a jog", "go for a swim",
    "go for ajog", "go out for a meal", "go through notes", "good behaviour",
    "good command of English", "good grades", "good manners", "great demand",
    "group activities", "grow crops", "grow faster", "handle complaints",
    "hands-on experience", "hang out with friends", "have a", "have a broader view of life",
    "have a chat", "have a clear idea", "have a coffee", "have a good command of English",
    "have a good grasp of", "help needy people", "high-rise buildings", "high-yield crops",
    "highly competitive", "historic building", "historic buildings", "historic site",
    "human activities", "hunting instincts", "impose sanctions on", "impose their opinions on others",
    "impoverished countries", "improve air quality", "improve communication skills", "improve efficiency",
    "improve practical skills", "improve their lives", "increase blood circulation", "increase hands-on experience",
    "increase ratings", "increase their earnings", "increase yields", "increasingly crowded",
    "increasingly smoggy", "intense competition", "intensive farming", "interest-free loans",
    "interpret messages", "keep a body shape", "keep a good body shape", "keep fit",
    "keep pace with", "keep pace with the demand", "keep up to date with", "key concepts",
    "lack self-discipline", "land-scarce cities", "landfill sites", "last but not least",
    "lead a hectic life", "lead a lavish life", "lead a team", "lead an inactive life",
    "leadership skills", "life experience", "life skills", "listen to others",
    "live a comfortable life", "live a frugal life", "live comfortably", "live events",
    "lively and stimulating", "locked in cages", "lose freedom", "maintain a clean water supply",
    "maintain a lifelong relationship", "maintain discipline", "maintain enthusiasm for studies", "maintain these buildings",
    "make a rash", "make a rash decision", "make a trip", "make decisions as a group",
    "make ends meet", "make good friends", "make new friends", "make non-essential trips",
    "make room for", "make the trip", "make way for", "male-dominated industries",
    "manage time effectively", "managerial skills", "match interests", "match needs",
    "material possessions", "mathematical talents", "mechanised farming", "meet the growing demand for",
    "members of the board", "middle-aged people", "mobilise resources", "moderate intensity activities",
    "moderate intensity activities increase blood circulation", "monitor progress", "moral principles and values", "most of the time",
    "motivated by greed", "move to", "needy people", "negative impact",
    "not very sociable", "obey rules", "offer discounts", "oil drilling",
    "older people", "organisational skills", "out of touch with the world", "overconsumption of goods",
    "passionate about", "pay a mortgage", "pay bills", "pay by credit card",
    "pay off debts", "people in need", "place an order", "places for doing outdoor activities",
    "plant life", "plant trees", "play basketball", "play chess",
    "pleasurable experience", "poor air quality", "poor sanitation", "poorly educated",
    "population expansion", "population explosion", "population is mobile", "practical experience",
    "practical problems", "practise singing", "prepare a Chinese meal refreshing drinks", "prepare for adulthood",
    "prepare meals", "prestigious cars", "prestigious universities", "price war",
    "process documents", "protective clothes", "provide shade", "provide shelter for",
    "provide the shade", "provincial towns", "purchase equipment", "pursue material goods",
    "put animal experimentation under scrutiny", "put me in an advantageous position", "put recyclable items", "reach a crossroads",
    "receive intensive training", "receive training", "reduce anxiety", "reduce sick leave",
    "regulate behaviour", "relive these experiences", "relocate to", "relocate to cities",
    "remove colours", "renowned institutions", "repetitive tasks", "resistant to change",
    "resistant to pests", "responsive to emotional needs", "reused effectively", "run out of time",
    "running cost", "satisfy the needs", "save time", "save/ shorten time",
    "search engines", "searching the web", "searching the web for information about", "self-made celebrities",
    "senior people", "set rules", "set up a company", "severe consequences",
    "share interests", "shatter the glass ceiling", "show compassion", "show discipline",
    "show good listening skills", "show off", "show patience", "show perseverance",
    "show their status", "sick leave", "side effect", "skills related to",
    "soccer and cricket", "soft skills", "solve problems", "sooner or later",
    "space missions", "space science", "spare time", "speak fluent English",
    "special effects", "specialise in", "specialise in a subject", "spend more than they earn",
    "spend quality time", "stand out from the crowd", "star famous actors and actresses", "stay in touch with",
    "store pictures", "styles in", "suffer injuries", "surveillance cameras",
    "sustain our civilisation", "tackle problems", "take a brisk walk", "take a gap year",
    "take a walk", "take an order from", "take notes", "take one year off",
    "take over on leave", "take photos", "take pictures", "take three days off",
    "taking a gap year", "talking points", "tap water", "tasks and responsibilities",
    "tasks at hand", "team assignments", "tend to be aggressive", "test the safety of products",
    "the farming sector", "the life experience", "the most advanced model of", "the running cost",
    "the times", "the variety of food", "the yield of farmland", "the younger generation",
    "they may feel that they are behind", "think twice", "third World countries", "those who visit these buildings can",
    "top universities", "toxic chemicals", "toxic substances", "trap heat from the sun",
    "tree-lined avenues", "turn on the taps", "uncover benefits", "undergo specialised training",
    "undergo training", "unusually warm conditions", "up-to-date equipment improve self-esteem", "upgrade skills",
    "upload photos", "use preservatives", "valuable services/essential services", "virtues into",
    "visit friends", "visual experience", "visual information", "vocational training",
    "want autonomy", "wear uniform", "wear uniforms", "western countries",
    "whether or not these products are functional", "wind down", "within walking distance", "world famous universities",
    "worth a visit", "write a report", "you should say", "you would say",
    "your experience"
  ],
  "城市与生活": [
    "a deterrent effect", "a good deterrent", "accommodate people", "affluent suburb",
    "air transport", "city dwellers", "community cohesion", "commute to work",
    "demand for housing", "experience a different culture", "high cost of living", "housing developers",
    "human-caused disturbances", "integrated different musical", "low-density neighbourhoods", "metropolis",
    "move to suburbs or rural areas", "nag parents to", "parenting styles", "poor access to transport",
    "public transport", "redevelop run-down urban areas", "reduce traffic congestion", "residential areas",
    "residential buildings", "rush-hour traffic", "take different factors into consideration", "traditions and character of this city",
    "traffic congestion", "transport costs", "travel a long distance commuting time", "urban life",
    "urban planning", "urban sprawl"
  ],
  "媒体与广告": [
    "alleviate the pressure", "be used commercially", "celebrity endorsement", "commercialise culture",
    "domestically produced films", "express ideas", "facial expression", "go to the cinema",
    "high-quality films", "live coverage of", "locally produced films", "mass media",
    "misleading advertisements", "news outlets", "peer pressure", "pervasive advertising",
    "put pressure on", "shape public opinion", "social networking", "talented filmmakers",
    "top-grossing films", "used commercially", "video chat programme", "watch news on TV",
    "watch videos"
  ],
  "工作与经济": [
    "a consumer culture", "a good career prospect", "a good work ethic", "a part-time job",
    "a tedious job", "a well-paid job", "achieve career success", "acquire professional skills",
    "adapt to the workplace", "advance one's career", "afford basic necessities", "an investment of time and money",
    "balance work and family commitments", "become professionals", "box office", "build good working relationships",
    "business leaders", "business opportunities", "business plans", "career advancement",
    "career opportunities", "career path", "career prospects", "career success",
    "charity work", "clerical work", "collaborative teamwork", "combine work and family commitments",
    "combine work and raising a family", "combine work with pleasure", "complete work on time", "concentrate on work",
    "consumer demand", "consumer goods", "consumer products", "consumer societies",
    "create employment", "create revenues", "deepen my understanding of run an office", "earn a higher salary",
    "earn as much money", "earn high profits", "earn more money", "earn more profits",
    "earn profits", "economic growth", "economic pressure", "economic value",
    "employment opportunities", "employment opportunities text messaging", "enter the workforce", "feed family create jobs",
    "financial difficulties", "financial institutions", "financial support", "find a decent job",
    "find employment", "find work", "flexible working hours", "focus on their work",
    "generate revenues", "good value for money", "have a fulflling career", "impress employers",
    "improve job prospects", "improve job skills", "increase productivity", "increase work experience",
    "intensely competitive unemployment rate", "job satisfaction", "job security", "job skills",
    "labour market", "lack money", "lose jobs", "low income families",
    "low income people", "make easy money", "make fast money", "make more profits",
    "make profits", "manual work", "non-financial factors", "not-for-profit organisations",
    "offer greater employment possibilities", "office equipment", "open the door to job opportunities", "overcome homesickness get off work",
    "practical work", "prepare for working lives", "present a professional image", "professional reporters",
    "professional trainers", "pursue a career", "put money in", "raise money for charity",
    "raising money for charity", "replace human labour", "run a successful business", "search for a job",
    "serve a niche market", "shop owner", "shopping malls", "steady income",
    "steady jobs", "suburban commuters", "tedious job", "the film industry",
    "the housing market", "the pharmacy industry", "travel to work", "well-paid jobs",
    "well-run shop", "well-suited to a job", "well-suited to ajob", "women in the Workplace",
    "work as a team", "work as a volunteer", "work as part of a team", "work at home",
    "work closely together with their peers", "work collaboratively", "work collaboratively with others", "work from home",
    "work overtime", "work placements", "work-life balance", "working alone",
    "working lives", "working people", "workplace performance"
  ],
  "政府与社会": [
    "a sense of community", "a social activity", "adopt measures", "allocate resources",
    "an international conference took a vacation", "big-budget films", "break the cycle of poverty", "break the law",
    "community cohesion", "congestion tax", "consumer Society", "consumer society",
    "devoted fans", "disadvantaged people", "disadvantaged people living in impoverished countries", "get rid of poverty",
    "government Intervention", "government action", "government intervention", "hold back social progress",
    "impose a tobacco tax on", "impose regulations", "international language", "international organisations",
    "introduce laws", "launch awareness campaigns", "launch massive campaigns", "law enforcement",
    "live in poverty", "make laws", "members of community", "mislead the public",
    "multinational enterprise", "offer a full refund", "open to the public", "part of community",
    "productive members of society", "protect the public", "provide subsidies", "public hospitals",
    "public services", "public transport service", "raise funds", "reduce inequality",
    "reduce poverty", "senior citizens", "social activity", "social networking websites",
    "social networking websites/social media", "social rules", "social welfare", "socialise with neighbours",
    "state housing", "stringent laws", "tax revenue", "tighten regulations on",
    "use public transport", "violate laws"
  ],
  "教育": [
    "a different education system", "academic performance", "academic skills", "academic work",
    "academically gifted", "achieve academic success", "acquire knowledge", "advance our knowledge",
    "afford tuition", "afford tuition fees", "an in-depth knowledge of", "areas of knowledge",
    "attend a prestigious university", "attend courses", "attend lectures", "attend online courses",
    "attend school", "before exams", "bright students", "broaden one's horizons",
    "build schools", "cheat in exams", "children start school", "complete a degree",
    "computer literacy", "cultivate critical thinking", "curriculum content", "direction from teachers",
    "drop out of school", "educational games", "engage students", "enter university",
    "exam factories", "exempted from tuition fees", "expand knowledge", "fill knowledge gaps",
    "final exams", "find enjoyment in school lives", "finish high school", "follow school rules",
    "free education", "further education", "go to university", "graduate from the university",
    "graduate from university", "have equal access to education", "higher education", "improve literacy",
    "increase knowledge", "keep pace with peers", "knowledge-based economy", "language school",
    "learn English", "learn managerial skills", "learning many things by heart", "learning outcomes",
    "leave school", "memorise key concepts", "nearly the exam time", "offer scholarships",
    "practical skills", "preferred areas of study", "prepare for exams", "pursue a degree",
    "qualities of students", "receive a formal education", "receive a formal education for free", "receive a university education",
    "receive a well-rounded education", "recruit teachers", "rote learning", "school curriculum",
    "set a bad example", "set bad examples", "start school", "study a subject",
    "study at university", "study from home", "study hard", "study independently",
    "study techniques", "study with enthusiasm", "take postgraduate courses", "take subject courses",
    "teach classes", "teach courses", "teach lessons", "teaching methods",
    "the education system", "the equal access to education", "the exam time", "the school system/the education system",
    "top student", "traditional classroom", "vital sources of knowledge", "vocational courses",
    "well-rounded education"
  ],
  "犯罪与法律": [
    "a prison sentence", "act as a deterrent", "an escaping criminal", "armed police",
    "breach of law", "catch criminals", "combat crime", "commit a crime",
    "commit crimes", "curb crime", "escape punishment", "face any punishment",
    "impose harsh punishment", "prevent crime", "prevent some crimes", "reduce recidivism",
    "rehabilitate offenders", "sensationalise crime", "serve a prison term", "shoot an escaping criminal"
  ],
  "环境": [
    "a natural talent in", "a source of pollution", "a view of nature", "air pollution",
    "alternative energy sources", "biodiversity loss", "car emissions", "carbon emissions",
    "categorise waste", "cause damage to the environment", "change natural behabiour", "climate change",
    "contaminate the environment", "dispose of waste", "ecological balance", "emissions from aircrafts",
    "endangered language", "endangered species", "environmental awareness", "environmental degradation",
    "environmental problems", "environmental responsibilities", "global Warming", "go green",
    "greenhouse gases", "habitable planet", "habitable planets", "habitat destruction",
    "harm wildlife", "home environment", "household waste", "mitigate climate change",
    "natural talent in", "preserve biodiversity", "protect endangered species", "reintroduce these animals to natural habitats",
    "sustainable development", "sustainable materials", "the hostile environment", "the loss of biodiversity",
    "traditional fossil fuels", "water pollution", "wildlife Preservation"
  ],
  "生活方式": [
    "a sedentary lifestyle", "buying habits", "cater for the needs of travellers", "classical music",
    "cover living expenses", "cut stress", "develop positive habits", "dinner party",
    "expand the readership", "extravagant parties", "extreme sports", "famous entertainers",
    "feel relaxed", "feel stressed", "have winter or summer holidays", "impart a clear code of conduct",
    "integrate musical styles", "lead a life of luxury", "leisure activities", "living conditions",
    "living standards", "love sport", "make a living", "music lover",
    "musical shows", "old-fashioned ideas", "outdoor games", "play extreme sports",
    "play sport", "playing sport", "pursue a hobby", "read books",
    "read through notes", "reduce stress", "rock music", "scenic sports",
    "spend a nice weekend", "sports stars", "start from scratch", "stressed out",
    "summer holiday", "the habit of", "the operation of our department", "travel by underground",
    "travel expenses", "travel in outer space", "travel in space"
  ],
  "科技": [
    "a dopt advanced technology", "a portable device", "a strong appetite", "achieve happiness",
    "adopt advanced technology", "apply pesticides", "apply themselves to develop skills and abilities", "apply to",
    "appreciate the effort of every participant", "artificial intelligence", "automate production", "build up a network of contacts",
    "computer programmers", "computer skills", "connect to the Internet", "cutting-edge innovation",
    "design mobile phone apps", "digital divide", "download software", "e-commerce website",
    "fax machines", "hi-tech products", "household appliances", "improve farming techniques",
    "information overload", "lead a happy life", "online business", "online shopping",
    "online stores", "read news online", "remote communication", "run an online shop",
    "scientific breakthroughs", "shop online", "technological innovations", "technological proliferation",
    "telecommunications technology", "the latest gadgets", "they experience happiness from these", "use online communication tools",
    "watch films online", "watch online news", "web-based technology"
  ]
};

// 句中实时检测：基础表达 → 词伙升级（短语级，控制误报）
var CIHUO_ACTIVE = [
  { basic: "learn knowledge", cihuo: "acquire knowledge", note: "knowledge 搭配 acquire/gain，不搭配 learn（中式英语）" },
  { basic: "get knowledge", cihuo: "acquire knowledge", note: "改为 acquire knowledge 更地道" },
  { basic: "take measures", cihuo: "adopt measures", note: "采纳措施用 adopt measures 更正式" },
  { basic: "use measures", cihuo: "adopt measures", note: "采纳措施用 adopt measures" },
  { basic: "make pollution", cihuo: "cause air pollution", note: "造成污染用 cause pollution / lead to environmental damage" },
  { basic: "big city", cihuo: "metropolis", note: "big city 偏口语，正式写作用 metropolis / major city" },
  { basic: "good for the environment", cihuo: "beneficial to the environment", note: "good 过泛，用 beneficial / have a positive impact on the environment" },
  { basic: "help the environment", cihuo: "benefit the environment", note: "用 benefit / have a positive effect on the environment" },
  { basic: "rich country", cihuo: "affluent country", note: "rich 偏口语，用 affluent / wealthy" },
  { basic: "poor people", cihuo: "disadvantaged groups", note: "poor people 偏口语，用 disadvantaged groups / those in poverty" },
  { basic: "a lot of money", cihuo: "a substantial amount of money", note: "a lot of 偏口语，正式写作替换" },
  { basic: "make a decision", cihuo: "reach a decision", note: "更正式搭配 reach / arrive at a decision" },
  { basic: "find a job", cihuo: "secure employment", note: "正式写作用 secure employment / obtain a position" },
  { basic: "get a job", cihuo: "secure employment", note: "正式写作用 secure employment" },
  { basic: "bad effect", cihuo: "adverse effect", note: "bad 偏口语，用 adverse / negative effect" },
  { basic: "good effect", cihuo: "positive impact", note: "good effect 偏口语，用 positive impact / beneficial effect" },
  { basic: "more and more", cihuo: "an increasing number of", note: "more and more 偏口语，用 an increasing number of / a growing number of" },
  { basic: "very important", cihuo: "crucial / vital", note: "very + 形容词偏口语，用单一强形容词" },
  { basic: "very big", cihuo: "substantial / considerable", note: "very big 偏口语，用 substantial / considerable" },
  { basic: "very good", cihuo: "excellent / outstanding", note: "very good 偏口语，用强形容词" },
];
