// ============================================================
//  官方考官范文库 (IELTS Examiner's Model Answers)
//  来源：雅思官方考官范文 PDF（大作文 22 篇 / 小作文 30 篇）
//        内容为考官亲写示范文，题目与范文一一对应
//  用途：批改后「范文对照」参考，非套话模板
//  注意：仅适用于 IELTS 类别，与其他考试无关
// ============================================================

var EXAMINER_ESSAYS = [
  // ---------------- Task 2 大作文 ----------------
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Some people think that strict punishments for driving offences are the key to reducing traffic accidents. Others, however, believe that other measures would be more effective in improving road safety. Discuss both these views and give your own opinion.",
    band: "9", words: 269,
    text: "People have differing views with regard to the question of how to make our roads safer. In my view, both punishments and a range of other measures can be used together to promote better driving habits.\n\nOn the one hand, strict punishments can certainly help to encourage people to drive more safely. Penalties for dangerous drivers can act as a deterrent, meaning that people avoid repeating the same offence. There are various types of driving penalty, such as small fines, licence suspension, driver awareness courses, and even prison sentences. The aim of these punishments is to show dangerous drivers that their actions have negative consequences. As a result, we would hope that drivers become more disciplined and alert, and that they follow the rules more carefully.\n\nOn the other hand, I believe that safe driving can be promoted in several different ways that do not punish drivers. Firstly, it is vitally important to educate people properly before they start to drive, and this could be done in schools or even as part of an extended or more difficult driving test. Secondly, more attention could be paid to safe road design. For example, signs can be used to warn people, speed bumps and road bends can be added to calm traffic, and speed cameras can help to deter people from driving too quickly. Finally, governments or local councils could reduce road accidents by investing in better public transport, which would mean that fewer people would need to travel by car.\n\nIn conclusion, while punishments can help to prevent bad driving, I believe that other road safety measures should also be introduced."
  },
  {
    type: "task2", subtype: "原因分析+利弊判断",
    title: "These days more fathers stay at home and take care of their children while mothers go out to work. What could be the reasons for this? Do you think it is a positive or a negative development?",
    band: "9", words: 274,
    text: "It is true that men are increasingly likely to take on the role of househusband, while more women than ever are the breadwinners in their families. There could be several reasons for this, and I consider it to be a very positive trend.\n\nIn recent years, parents have had to adapt to various changes in our societies. Equal rights movements have made great progress, and it has become normal for women to gain qualifications and pursue a career. It has also become socially acceptable for men to stay at home and look after their children. At the same time, the rising cost of living has meant that both marriage partners usually need to work and save money before starting a family. Therefore, when couples have children, they may decide who works and who stays at home depending on the personal preference of each partner, or based on which partner earns the most money.\n\nIn my view, the changes described above should be seen as progress. We should be happy to live in a society in which men and women have equal opportunities, and in which women are not put under pressure to sacrifice their careers. Equally, it seems only fair that men should be free to leave their jobs in order to assume childcare responsibilities if this is what they wish to do. Couples should be left to make their own decisions about which parental role each partner takes, according to their particular circumstances and needs.\n\nIn conclusion, the changing roles of men and women in the family are a result of wider changes in society, and I believe that these developments are desirable."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Wild animals have no place in the 21st century, so protecting them is a waste of resources. To what extent do you agree or disagree?",
    band: "9", words: 269,
    text: "Some people argue that it is pointless to spend money on the protection of wild animals because we humans have no need for them. I completely disagree with this point of view.\n\nIn my opinion, it is absurd to argue that wild animals have no place in the 21st century. I do not believe that planet Earth exists only for the benefit of humans, and there is nothing special about this particular century that means that we suddenly have the right to allow or encourage the extinction of any species. Furthermore, there is no compelling reason why we should let animals die out. We do not need to exploit or destroy every last square metre of land in order to feed or accommodate the world's population. There is plenty of room for us to exist side by side with wild animals, and this should be our aim.\n\nI also disagree with the idea that protecting animals is a waste of resources. It is usually the protection of natural habitats that ensures the survival of wild animals, and most scientists agree that these habitats are also crucial for human survival. For example, rainforests produce oxygen, absorb carbon dioxide and stabilise the Earth's climate. If we destroyed these areas, the costs of managing the resulting changes to our planet would far outweigh the costs of conservation. By protecting wild animals and their habitats, we maintain the natural balance of all life on Earth.\n\nIn conclusion, we have no right to decide whether or not wild animals should exist, and I believe that we should do everything we can to protect them."
  },
  {
    type: "task2", subtype: "原因+要素分析",
    title: "Happiness is considered very important in life. Why is it difficult to define? What factors are important in achieving happiness?",
    band: "9", words: 292,
    text: "It is no doubt true that the majority of people would like to be happy in their lives. While the personal nature of happiness makes it difficult to describe, there do seem to be some common needs that we all share with regard to experiencing or achieving happiness.\n\nHappiness is difficult to define because it means something different to each individual person. Nobody can fully understand or experience another person's feelings, and we all have our own particular passions from which we take pleasure. Some people, for example, derive a sense of satisfaction from earning money or achieving success, whereas for others, health and family are much more important. At the same time, a range of other feelings, from excitement to peacefulness, may be associated with the idea of happiness, and the same person may therefore feel happy in a variety of different ways.\n\nAlthough it seems almost impossible to give a precise definition of happiness, most people would agree that there are some basic preconditions to achieving it. Firstly, it is hard for a person to be happy if he or she does not have a safe place to live and enough food to eat. Our basic survival needs must surely be met before we can lead a pleasant life. Secondly, the greatest joy in life is usually found in shared experiences with family and friends, and it is rare to find a person who is content to live in complete isolation. Other key factors could be individual freedom and a sense of purpose in life.\n\nIn conclusion, happiness is difficult to define because it is particular to each individual, but I believe that our basic needs for shelter, food and company need to be fulfilled before we can experience it."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Families who send their children to private schools should not be required to pay taxes that support the state education system. To what extent do you agree or disagree with this statement?",
    band: "9", words: 269,
    text: "Some people believe that parents of children who attend private schools should not need to contribute to state schools through taxes. Personally, I completely disagree with this view.\n\nFor a variety of reasons, it would be wrong to reduce taxes for families who pay for private education. Firstly, it would be difficult to calculate the correct amount of tax reduction for these families, and staff would be required to manage this complex process. Secondly, we all pay a certain amount of tax for public services that we may not use. For example, most people are fortunate enough not to have to call the police or fire brigade at any time in their lives, but they would not expect a tax reduction for this. Finally, if wealthy families were given a tax discount for sending their children to private schools, we might have a situation where poorer people pay higher taxes than the rich.\n\nIn my opinion, we should all be happy to pay our share of the money that supports public schools. It is beneficial for all members of society to have a high quality education system with equal opportunities for all young people. This will result in a well-educated workforce, and in turn a more productive and prosperous nation. Parents of children in private schools may also see the advantages of this in their own lives. For example, a company owner will need well qualified and competent staff, and a well-funded education system can provide such employees.\n\nIn conclusion, I do not believe that any financial concessions should be made for people who choose private education."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "When choosing a job, the salary is the most important consideration. To what extent do you agree or disagree?",
    band: "9", words: 275,
    text: "Many people choose their jobs based on the size of the salary offered. Personally, I disagree with the idea that money is the key consideration when deciding on a career, because I believe that other factors are equally important.\n\nOn the one hand, I agree that money is necessary in order for people to meet their basic needs. For example, we all need money to pay for housing, food, bills, health care, and education. Most people consider it a priority to at least earn a salary that allows them to cover these needs and have a reasonable quality of life. If people chose their jobs based on enjoyment or other non-financial factors, they might find it difficult to support themselves. Artists and musicians, for instance, are known for choosing a career path that they love, but that does not always provide them with enough money to live comfortably and raise a family.\n\nNevertheless, I believe that other considerations are just as important as what we earn in our jobs. Firstly, personal relationships and the atmosphere in a workplace are extremely important when choosing a job. Having a good manager or friendly colleagues, for example, can make a huge difference to workers' levels of happiness and general quality of life. Secondly, many people's feelings of job satisfaction come from their professional achievements, the skills they learn, and the position they reach, rather than the money they earn. Finally, some people choose a career because they want to help others and contribute something positive to society.\n\nIn conclusion, while salaries certainly affect people's choice of profession, I do not believe that money outweighs all other motivators."
  },
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Some people think that in the modern world we are more dependent on each other, while others think that people have become more independent. Discuss both views and give your own opinion.",
    band: "7-9", words: 279,
    text: "People have different views about whether we are more or less dependent on others nowadays. In my view, modern life forces us to be more independent than people were in the past.\n\nThere are two main reasons why it could be argued that we are more dependent on each other now. Firstly, life is more complex and difficult, especially because the cost of living has increased so dramatically. For example, young adults tend to rely on their parents for help when buying a house. Property prices are higher than ever, and without help it would be impossible for many people to pay a deposit and a mortgage. Secondly, people seem to be more ambitious nowadays, and they want a better quality of life for their families. This means that both parents usually need to work full-time, and they depend on support from grandparents and babysitters for child care.\n\nHowever, I would agree with those who believe that people are more independent these days. In most countries, families are becoming smaller and more dispersed, which means that people cannot count on relatives as much as they used to. We also have more freedom to travel and live far away from our home towns. For example, many students choose to study abroad instead of going to their local university, and this experience makes them more independent as they learn to live alone. Another factor in this growing independence is technology, which allows us to work alone and from any part of the world.\n\nIn conclusion, while there are some reasons to believe that people now depend on each other more, my own view is that we are more independent than ever."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Foreign visitors should pay more than local visitors for cultural and historical attractions. To what extent do you agree or disagree with this opinion?",
    band: "9", words: 269,
    text: "It is sometimes argued that tourists from overseas should be charged more than local residents to visit important sites and monuments. I completely disagree with this idea.\n\nThe argument in favour of higher prices for foreign tourists would be that cultural or historical attractions often depend on state subsidies to keep them going, which means that the resident population already pays money to these sites through the tax system. However, I believe this to be a very shortsighted view. Foreign tourists contribute to the economy of the host country with the money they spend on a wide range of goods and services, including food, souvenirs, accommodation and travel. The governments and inhabitants of every country should be happy to subsidise important tourist sites and encourage people from the rest of the world to visit them.\n\nIf travellers realised that they would have to pay more to visit historical and cultural attractions in a particular nation, they would perhaps decide not to go to that country on holiday. To take the UK as an example, the tourism industry and many related jobs rely on visitors coming to the country to see places like Windsor Castle or Saint Paul's Cathedral. These two sites charge the same price regardless of nationality, and this helps to promote the nation's cultural heritage. If overseas tourists stopped coming due to higher prices, there would be a risk of insufficient funding for the maintenance of these important buildings.\n\nIn conclusion, I believe that every effort should be made to attract tourists from overseas, and it would be counterproductive to make them pay more than local residents."
  },
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Nowadays animal experiments are widely used to develop new medicines and to test the safety of other products. Some people argue that these experiments should be banned because it is morally wrong to cause animals to suffer, while others are in favour of them because of their benefits to humanity. Discuss both views and give your own opinion.",
    band: "9", words: 268,
    text: "It is true that medicines and other products are routinely tested on animals before they are cleared for human use. While I tend towards the viewpoint that animal testing is morally wrong, I would have to support a limited amount of animal experimentation for the development of medicines.\n\nOn the one hand, there are clear ethical arguments against animal experimentation. To use a common example of this practice, laboratory mice may be given an illness so that the effectiveness of a new drug can be measured. Opponents of such research argue that humans have no right to subject animals to this kind of trauma, and that the lives of all creatures should be respected. They believe that the benefits to humans do not justify the suffering caused, and that scientists should use alternative methods of research.\n\nOn the other hand, reliable alternatives to animal experimentation may not always be available. Supporters of the use of animals in medical research believe that a certain amount of suffering on the part of mice or rats can be justified if human lives are saved. They argue that opponents of such research might feel differently if a member of their own families needed a medical treatment that had been developed through the use of animal experimentation. Personally, I agree with the banning of animal testing for non-medical products, but I feel that it may be a necessary evil where new drugs and medical procedures are concerned.\n\nIn conclusion, it seems to me that it would be wrong to ban testing on animals for research until equally effective alternatives have been developed."
  },
  {
    type: "task2", subtype: "问题+措施",
    title: "In the developed world, average life expectancy is increasing. What problems will this cause for individuals and society? Suggest some measures that could be taken to reduce the impact of ageing populations.",
    band: "9", words: 265,
    text: "It is true that people in industrialised nations can expect to live longer than ever before. Although there will undoubtedly be some negative consequences of this trend, societies can take steps to mitigate these potential problems.\n\nAs people live longer and the populations of developed countries grow older, several related problems can be anticipated. The main issue is that there will obviously be more people of retirement age who will be eligible to receive a pension. The proportion of younger, working adults will be smaller, and governments will therefore receive less money in taxes in relation to the size of the population. In other words, an ageing population will mean a greater tax burden for working adults. Further pressures will include a rise in the demand for healthcare, and the fact young adults will increasingly have to look after their elderly relatives.\n\nThere are several actions that governments could take to solve the problems described above. Firstly, a simple solution would be to increase the retirement age for working adults, perhaps from 65 to 70. Nowadays, people of this age tend to be healthy enough to continue a productive working life. A second measure would be for governments to encourage immigration in order to increase the number of working adults who pay taxes. Finally, money from national budgets will need to be taken from other areas and spent on vital healthcare, accommodation and transport facilities for the rising numbers of older citizens.\n\nIn conclusion, various measures can be taken to tackle the problems that are certain to arise as the populations of countries grow older."
  },
  {
    type: "task2", subtype: "利弊比较",
    title: "Some people regard video games as harmless fun, or even as a useful educational tool. Others, however, believe that videos games are having an adverse effect on the people who play them. In your opinion, do the drawbacks of video games outweigh the benefits?",
    band: "9", words: 258,
    text: "Many people, and children in particular, enjoy playing computer games. While I accept that these games can sometimes have a positive effect on the user, I believe that they are more likely to have a harmful impact.\n\nOn the one hand, video games can be both entertaining and educational. Users, or gamers, are transported into virtual worlds which are often more exciting and engaging than real-life pastimes. From an educational perspective, these games encourage imagination and creativity, as well as concentration, logical thinking and problem solving, all of which are useful skills outside the gaming context. Furthermore, it has been shown that computer simulation games can improve users' motor skills and help to prepare them for real-world tasks, such as flying a plane.\n\nHowever, I would argue that these benefits are outweighed by the drawbacks. Gaming can be highly addictive because users are constantly given scores, new targets and frequent rewards to keep them playing. Many children now spend hours each day trying to progress through the levels of a game or to get a higher score than their friends. This type of addiction can have effects ranging from lack of sleep to problems at school, when homework is sacrificed for a few more hours on the computer or console. The rise in obesity in recent years has also been linked in part to the sedentary lifestyle and lack of exercise that often accompany gaming addiction.\n\nIn conclusion, it seems to me that the potential dangers of video games are more significant than the possible benefits."
  },
  {
    type: "task2", subtype: "原因+比较论述",
    title: "There are many different types of music in the world today. Why do we need music? Is the traditional music of a country more important than the international music that is heard everywhere nowadays?",
    band: "9", words: 261,
    text: "It is true that a rich variety of musical styles can be found around the world. Music is a vital part of all human cultures for a range of reasons, and I would argue that traditional music is more important than modern, international music.\n\nMusic is something that accompanies all of us throughout our lives. As children, we are taught songs by our parents and teachers as a means of learning language, or simply as a form of enjoyment. Children delight in singing with others, and it would appear that the act of singing in a group creates a connection between participants, regardless of their age. Later in life, people's musical preferences develop, and we come to see our favourite songs as part of our life stories. Music both expresses and arouses emotions in a way that words alone cannot. In short, it is difficult to imagine life without it.\n\nIn my opinion, traditional music should be valued over the international music that has become so popular. International pop music is often catchy and fun, but it is essentially a commercial product that is marketed and sold by business people. Traditional music, by contrast, expresses the culture, customs and history of a country. Traditional styles, such as ...(example)..., connect us to the past and form part of our cultural identity. It would be a real pity if pop music became so predominant that these national styles disappeared.\n\nIn conclusion, music is a necessary part of human existence, and I believe that traditional music should be given more importance than international music."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Some people think that all teenagers should be required to do unpaid work in their free time to help the local community. They believe this would benefit both the individual teenager and society as a whole. Do you agree or disagree?",
    band: "9", words: 250,
    text: "Many young people work on a volunteer basis, and this can only be beneficial for both the individual and society as a whole. However, I do not agree that we should therefore force all teenagers to do unpaid work.\n\nMost young people are already under enough pressure with their studies, without being given the added responsibility of working in their spare time. School is just as demanding as a full-time job, and teachers expect their students to do homework and exam revision on top of attending lessons every day. When young people do have some free time, we should encourage them to enjoy it with their friends or to spend it doing sports and other leisure activities. They have many years of work ahead of them when they finish their studies.\n\nAt the same time, I do not believe that society has anything to gain from obliging young people to do unpaid work. In fact, I would argue that it goes against the values of a free and fair society to force a group of people to do something against their will. Doing this can only lead to resentment amongst young people, who would feel that they were being used, and parents, who would not want to be told how to raise their children. Currently, nobody is forced to volunteer, and this is surely the best system.\n\nIn conclusion, teenagers may choose to work for free and help others, but in my opinion we should not make this compulsory."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Some people believe that hobbies need to be difficult to be enjoyable. To what extent do you agree or disagree?",
    band: "9", words: 266,
    text: "Some hobbies are relatively easy, while others present more of a challenge. Personally, I believe that both types of hobby can be fun, and I therefore disagree with the statement that hobbies need to be difficult in order to be enjoyable.\n\nOn the one hand, many people enjoy easy hobbies. One example of an activity that is easy for most people is swimming. This hobby requires very little equipment, it is simple to learn, and it is inexpensive. I remember learning to swim at my local swimming pool when I was a child, and it never felt like a demanding or challenging experience. Another hobby that I find easy and fun is photography. In my opinion, anyone can take interesting pictures without knowing too much about the technicalities of operating a camera. Despite being straightforward, taking photos is a satisfying activity.\n\nOn the other hand, difficult hobbies can sometimes be more exciting. If an activity is more challenging, we might feel a greater sense of satisfaction when we manage to do it successfully. For example, film editing is a hobby that requires a high level of knowledge and expertise. In my case, it took me around two years before I became competent at this activity, but now I enjoy it much more than I did when I started. I believe that many hobbies give us more pleasure when we reach a higher level of performance because the results are better and the feeling of achievement is greater.\n\nIn conclusion, simple hobbies can be fun and relaxing, but difficult hobbies can be equally pleasurable for different reasons."
  },
  {
    type: "task2", subtype: "影响分析+利弊判断",
    title: "Nowadays the way many people interact with each other has changed because of technology. In what ways has technology affected the types of relationships that people make? Has this been a positive or negative development?",
    band: "9", words: 257,
    text: "It is true that new technologies have had an influence on communication between people. Technology has affected relationships in various ways, and in my opinion there are both positive and negative effects.\n\nTechnology has had an impact on relationships in business, education and social life. Firstly, telephones and the Internet allow business people in different countries to interact without ever meeting each other. Secondly, services like Skype create new possibilities for relationships between students and teachers. For example, a student can now take video lessons with a teacher in a different city or country. Finally, many people use social networks, like Facebook, to make new friends and find people who share common interests, and they interact through their computers rather than face to face.\n\nOn the one hand, these developments can be extremely positive. Cooperation between people in different countries was much more difficult when communication was limited to written letters or telegrams. Nowadays, interactions by email, phone or video are almost as good as face-to-face meetings, and many of us benefit from these interactions, either in work or social contexts. On the other hand, the availability of new communication technologies can also have the result of isolating people and discouraging real interaction. For example, many young people choose to make friends online rather than mixing with their peers in the real world, and these 'virtual' relationships are a poor substitute for real friendships.\n\nIn conclusion, technology has certainly revolutionised communication between people, but not all of the outcomes have been positive."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "We cannot help everyone in the world that needs help, so we should only be concerned with our own communities and countries. To what extent do you agree or disagree with this statement?",
    band: "9", words: 280,
    text: "Some people believe that we should not help people in other countries as long as there are problems in our own society. I disagree with this view because I believe that we should try to help as many people as possible.\n\nOn the one hand, I accept that it is important to help our neighbours and fellow citizens. In most communities there are people who are impoverished or disadvantaged in some way. It is possible to find homeless people, for example, in even the wealthiest of cities, and for those who are concerned about this problem, there are usually opportunities to volunteer time or give money to support these people. In the UK, people can help in a variety of ways, from donating clothing to serving free food in a soup kitchen. As the problems are on our doorstep, and there are obvious ways to help, I can understand why some people feel that we should prioritise local charity.\n\nAt the same time, I believe that we have an obligation to help those who live beyond our national borders. In some countries the problems that people face are much more serious than those in our own communities, and it is often even easier to help. For example, when children are dying from curable diseases in African countries, governments and individuals in richer countries can save lives simply by paying for vaccines that already exist. A small donation to an international charity might have a much greater impact than helping in our local area.\n\nIn conclusion, it is true that we cannot help everyone, but in my opinion national boundaries should not stop us from helping those who are in need."
  },
  {
    type: "task2", subtype: "观点论述",
    title: "In recent years, there has been growing interest in the relationship between equality and personal achievement. Some people believe that individuals can achieve more in egalitarian societies. Others believe that high levels of personal achievement are possible only if individuals are free to succeed or fail according to their individual merits. What is your view of the relationship between equality and personal success?",
    band: "9", words: 260,
    text: "In my opinion, an egalitarian society is one in which everyone has the same rights and the same opportunities. I completely agree that people can achieve more in this kind of society.\n\nEducation is an important factor with regard to personal success in life. I believe that all children should have access to free schooling, and higher education should be either free or affordable for all those who chose to pursue a university degree. In a society without free schooling or affordable higher education, only children and young adults from wealthier families would have access to the best learning opportunities, and they would therefore be better prepared for the job market. This kind of inequality would ensure the success of some but harm the prospects of others.\n\nI would argue that equal rights and opportunities are not in conflict with people's freedom to succeed or fail. In other words, equality does not mean that people lose their motivation to succeed, or that they are not allowed to fail. On the contrary, I believe that most people would feel more motivated to work hard and reach their potential if they thought that they lived in a fair society. Those who did not make the same effort would know that they had wasted their opportunity. Inequality, on the other hand, would be more likely to demotivate people because they would know that the odds of success were stacked in favour of those from privileged backgrounds.\n\nIn conclusion, it seems to me that there is a positive relationship between equality and personal success."
  },
  {
    type: "task2", subtype: "同意与否",
    title: "Universities should accept equal numbers of male and female students in every subject. To what extent do you agree or disagree?",
    band: "9", words: 265,
    text: "In my opinion, men and women should have the same educational opportunities. However, I do not agree with the idea of accepting equal proportions of each gender in every university subject.\n\nHaving the same number of men and women on all degree courses is simply unrealistic. Student numbers on any course depend on the applications that the institution receives. If a university decided to fill courses with equal numbers of males and females, it would need enough applicants of each gender. In reality, many courses are more popular with one gender than the other, and it would not be practical to aim for equal proportions. For example, nursing courses tend to attract more female applicants, and it would be difficult to fill these courses if fifty per cent of the places needed to go to males.\n\nApart from the practical concerns expressed above, I also believe that it would be unfair to base admission to university courses on gender. Universities should continue to select the best candidates for each course according to their qualifications. In this way, both men and women have the same opportunities, and applicants know that they will be successful if they work hard to achieve good grades at school. If a female student is the best candidate for a place on a course, it is surely wrong to reject her in favour of a male student with lower grades or fewer qualifications.\n\nIn conclusion, the selection of university students should be based on merit, and it would be both impractical and unfair to change to a selection procedure based on gender."
  },
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Some people think that museums should be enjoyable places to entertain people, while others believe that the purpose of museums is to educate. Discuss both views and give you own opinion.",
    band: "9", words: 253,
    text: "People have different views about the role and function of museums. In my opinion, museums can and should be both entertaining and educational.\n\nOn the one hand, it can be argued that the main role of a museum is to entertain. Museums are tourist attractions, and their aim is to exhibit a collection of interesting objects that many people will want to see. The average visitor may become bored if he or she has to read or listen to too much educational content, so museums often put more of an emphasis on enjoyment rather than learning. This type of museum is designed to be visually spectacular, and may have interactive activities or even games as part of its exhibitions.\n\nOn the other hand, some people argue that museums should focus on education. The aim of any exhibition should be to teach visitors something that they did not previously know. Usually this means that the history behind the museum's exhibits needs to be explained, and this can be done in various ways. Some museums employ professional guides to talk to their visitors, while other museums offer headsets so that visitors can listen to detailed commentary about the exhibition. In this way, museums can play an important role in teaching people about history, culture, science and many other aspects of life.\n\nIn conclusion, it seems to me that a good museum should be able to offer an interesting, enjoyable and educational experience so that people can have fun and learn something at the same time."
  },
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Some people believe that studying at university or college is the best route to a successful career, while others believe that it is better to get a job straight after school. Discuss both views and give your opinion.",
    band: "9", words: 271,
    text: "When they finish school, teenagers face the dilemma of whether to get a job or continue their education. While there are some benefits to getting a job straight after school, I would argue that it is better to go to college or university.\n\nThe option to start work straight after school is attractive for several reasons. Many young people want to start earning money as soon as possible. In this way, they can become independent, and they will be able to afford their own house or start a family. In terms of their career, young people who decide to find work, rather than continue their studies, may progress more quickly. They will have the chance to gain real experience and learn practical skills related to their chosen profession. This may lead to promotions and a successful career.\n\nOn the other hand, I believe that it is more beneficial for students to continue their studies. Firstly, academic qualifications are required in many professions. For example, it is impossible to become a doctor, teacher or lawyer without having the relevant degree. As a result, university graduates have access to more and better job opportunities, and they tend to earn higher salaries than those with fewer qualifications. Secondly, the job market is becoming increasingly competitive, and sometimes there are hundreds of applicants for one position in a company. Young people who do not have qualifications from a university or college will not be able to compete.\n\nFor the reasons mentioned above, it seems to me that students are more likely to be successful in their careers if they continue their studies beyond school level."
  },
  {
    type: "task2", subtype: "双边讨论+自己观点",
    title: "Several languages are in danger of extinction because they are spoken by very small numbers of people. Some people say that governments should spend public money on saving these languages, while others believe that would be a waste of money. Discuss both these views and give your opinion.",
    band: "9", words: 258,
    text: "It is true that some minority languages may disappear in the near future. Although it can be argued that governments could save money by allowing this to happen, I believe that these languages should be protected and preserved.\n\nThere are several reasons why saving minority languages could be seen as a waste of money. Firstly, if a language is only spoken by a small number of people, expensive education programmes will be needed to make sure that more people learn it, and the state will have to pay for facilities, teachers and marketing. This money might be better spent on other public services. Secondly, it would be much cheaper and more efficient for countries to have just one language. Governments could cut all kinds of costs related to communicating with each minority group.\n\nDespite the above arguments, I believe that governments should try to preserve languages that are less widely spoken. A language is much more than simply a means of communication; it has a vital connection with the cultural identity of the people who speak it. If a language disappears, a whole way of life will disappear with it, and we will lose the rich cultural diversity that makes societies more interesting. By spending money to protect minority languages, governments can also preserve traditions, customs and behaviours that are part of a country's history.\n\nIn conclusion, it may save money in the short term if we allow minority languages to disappear, but in the long term this would have an extremely negative impact on our cultural heritage."
  },
  {
    type: "task2", subtype: "问题+措施",
    title: "Explain some of the ways in which humans are damaging the environment. What can governments do to address these problems? What can individual people do?",
    band: "9", words: 250,
    text: "Humans are responsible for a variety of environmental problems, but we can also take steps to reduce the damage that we are causing to the planet. This essay will discuss environmental problems and the measures that governments and individuals can take to address these problems.\n\nTwo of the biggest threats to the environment are air pollution and waste. Gas emissions from factories and exhaust fumes from vehicles lead to global warming, which may have a devastating effect on the planet in the future. As the human population increases, we are also producing ever greater quantities of waste, which contaminates the earth and pollutes rivers and oceans.\n\nGovernments could certainly make more effort to reduce air pollution. They could introduce laws to limit emissions from factories or to force companies to use renewable energy from solar, wind or water power. They could also impose 'green taxes' on drivers and airline companies. In this way, people would be encouraged to use public transport and to take fewer flights abroad, therefore reducing emissions.\n\nIndividuals should also take responsibility for the impact they have on the environment. They can take public transport rather than driving, choose products with less packaging, and recycle as much as possible. Most supermarkets now provide reusable bags for shoppers as well as 'banks' for recycling glass, plastic and paper in their car parks. By reusing and recycling, we can help to reduce waste.\n\nIn conclusion, both national governments and individuals must play their part in looking after the environment."
  },

  // ---------------- Task 1 小作文 ----------------
  {
    type: "task1", subtype: "柱状图",
    title: "The chart below shows the total number of minutes (in billions) of telephone calls in the UK, divided into three categories, from 1995-2002.",
    band: "9", words: 197,
    tip: "4 段式提纲：Introduction 用自己的话改写题目 → Overview 指出哪类最高、哪类最低、哪类变化最大 → Details 对比 1995 年三类数据及到 1999 年的变化 → Details 观察 1999 年后 local calls 的变化并与其他两类对比，最后给出 2002 年数据对比。",
    text: "The bar chart compares the amount of time spent by people in the UK on three different types of phone call between 1995 and 2002.\n\nIt is clear that calls made via local, fixed lines were the most popular type, in terms of overall usage, throughout the period shown. The lowest figures on the chart are for mobile calls, but this category also saw the most dramatic increase in user minutes.\n\nIn 1995, people in the UK used fixed lines for a total of just over 70 billion minutes for local calls, and about half of that amount of time for national or international calls. By contrast, mobile phones were only used for around 4 billion minutes. Over the following four years, the figures for all three types of phone call increased steadily.\n\nBy 1999, the amount of time spent on local calls using landlines had reached a peak at 90 billion minutes. Subsequently, the figure for this category fell, but the rise in the other two types of phone call continued. In 2002, the number of minutes of national / international landline calls passed 60 billion, while the figure for mobiles rose to around 45 billion minutes."
  },
  {
    type: "task1", subtype: "柱状图+饼图",
    title: "The bar chart below shows the proportions of English men and women of different ages who were living alone in 2011. The pie chart compares the numbers of bedrooms in these one-person households.",
    band: "9", words: 189,
    tip: "注意：由于只有 20 分钟，被迫省略了柱状图中的部分信息是正常的。考官期待你挑选关键数据，而不是试图包含所有信息。",
    text: "The two charts give information about single-occupant households in England in the year 2011. The bar chart compares figures for occupants' age and gender, and the pie chart shows data about the number of bedrooms in these homes.\n\nOverall, females made up a higher proportion of people living alone than males, and this difference is particularly noticeable in the older age categories. We can also see that the most common number of bedrooms in a single-occupant home was two.\n\nA significant majority of the people aged 65 or over who were living alone in England in 2011 were female. Women made up around 72% of single occupants aged 75 to 84, and 76% of those aged 85 or over. By contrast, among younger adults the figures for males were higher. For example, in the 35-49 age category, men accounted for nearly 65% of people living alone.\n\nIn the same year, 35.4% of one-person households in England had two bedrooms, while one-bedroom and three-bedroom homes accounted for 28% and 29.8% of the total. Under 7% of single-occupant homes had four or more bedrooms."
  },
  {
    type: "task1", subtype: "表格",
    title: "The tables below give information about sales of Fairtrade*-labelled coffee and bananas in 1999 and 2004 in five European countries. (*Fairtrade: a category of products for which farmers from developing countries have been paid an officially agreed fair price.)",
    band: "9", words: 220,
    text: "The tables show the amount of money spent on Fairtrade coffee and bananas in two separate years in the UK, Switzerland, Denmark, Belgium and Sweden.\n\nIt is clear that sales of Fairtrade coffee rose in all five European countries from 1999 to 2004, but sales of Fairtrade bananas only went up in three out of the five countries. Overall, the UK saw by far the highest levels of spending on the two products.\n\nIn 1999, Switzerland had the highest sales of Fairtrade coffee, at €3 million, while revenue from Fairtrade bananas was highest in the UK, at €15 million. By 2004, however, sales of Fairtrade coffee in the UK had risen to €20 million, and this was over three times higher than Switzerland's sales figure for Fairtrade coffee in that year. The year 2004 also saw dramatic increases in the money spent on Fairtrade bananas in the UK and Switzerland, with revenues rising by €32 million and €4.5 million respectively.\n\nSales of the two Fairtrade products were far lower in Denmark, Belgium and Sweden. Small increases in sales of Fairtrade coffee can be seen, but revenue remained at €2 million or below in all three countries in both years. Finally, it is noticeable that the money spent on Fairtrade bananas actually fell in Belgium and Sweden."
  },
  {
    type: "task1", subtype: "示意图/地图",
    title: "The diagrams below show the site of a school in 2004 and the plan for changes to the school site in 2024.",
    band: "9", words: 183,
    text: "The two pictures compare the layout of a school as it was in the year 2004 with a proposed site design for the year 2024.\n\nIt is clear that the main change for 2024 involves the addition of a new school building. The school will then be able to accommodate a considerably larger number of students.\n\nIn 2004, there were 600 pupils attending the school, and the two school buildings were separated by a path running from the main entrance to the sports field. By 2024, it is expected that there will be 1000 pupils, and a third building will have been constructed. Furthermore, the plan is to join the two original buildings together, creating a shorter path that links the buildings only.\n\nAs the third building and a second car park will be built on the site of the original sports field, a new, smaller sports field will need to be laid. A new road will also be built from the main entrance to the second car park. Finally, no changes will be made to the main entrance and original car park."
  },
  {
    type: "task1", subtype: "柱状图/年龄结构",
    title: "The charts below compare the age structure of the populations of France and India in 1984.",
    band: "9", words: 199,
    text: "The two charts compare the populations of France and India in terms of age distribution by gender in the year 1984.\n\nIt is clear that the population of India was younger than that of France in 1984, with a noticeably larger proportion of people aged under 20. France, on the other hand, had a significantly larger percentage of elderly inhabitants.\n\nIn India, close to 14% of people were aged 5 or under, and each five-year age bracket above this contained an increasingly smaller proportion of the population. France's population, by contrast, was more evenly distributed across the age ranges, with similar figures (around 7% to 8% of all people) for each five-year cohort between the ages of 0 and 40. Somewhere between 10% and 15% of all French people were aged 70 or older, but the equivalent figure for India was only 2%.\n\nLooking more closely at gender, there was a noticeably higher proportion of French women than men in every cohort from age 50 upwards. For example, almost 3% of French 70- to 75-year-olds were women, while just under 2% were men. No significant gender differences can be seen on the Indian population chart."
  },
  {
    type: "task1", subtype: "饼图",
    title: "The pie charts below show how dangerous waste products are dealt with in three countries.",
    band: "9", words: 159,
    text: "The charts compare Korea, Sweden and the UK in terms of the methods used in each country to dispose of harmful waste.\n\nIt is clear that in both the UK and Sweden, the majority of dangerous waste products are buried underground. By contrast, most hazardous materials in the Republic of Korea are recycled.\n\nLooking at the information in more detail, we can see that 82% of the UK's dangerous waste is put into landfill sites. This disposal technique is used for 55% of the harmful waste in Sweden and only 22% of similar waste in Korea. The latter country recycles 69% of hazardous materials, which is far more than the other two nations.\n\nWhile 25% of Sweden's dangerous waste is recycled, the UK does not recycle at all. Instead, it dumps waste at sea or treats it chemically. These two methods are not employed in Korea or Sweden, which favour incineration for 9% and 20% of dangerous waste respectively."
  },
  {
    type: "task1", subtype: "示意图",
    title: "The diagrams below show how houses can be protected in areas which are prone to flooding.",
    band: "9", words: 184,
    text: "The diagrams compare two different methods of defence for homes which are at risk of being flooded.\n\nThe key difference between the diagrams is that they show flood protection with and without a stopbank. In either case, the at-risk home is raised on stilts above ground level.\n\nThe first diagram shows how a stopbank acts as a flood barrier to stop river water from flooding homes. The stopbank is a small mound of land next to the river that is higher than the 100-year flood level, and prevents the river from bursting its banks. Nearby houses can be built on stilts to prevent flooding from rainwater, and a floodgate beneath the stopbank can be opened to allow this 'ponding' to drain off into the river.\n\nWhen there is no stopbank, as shown in the second diagram, there will be nothing to stop the river from flooding. In this case, the solution is to put buildings on stilts. The height of the stilts is measured so that the floor of the house is 300mm above the 100-year flood level. This measurement is called the 'freeboard'."
  },
  {
    type: "task1", subtype: "表格",
    title: "The table below shows the amount of waste production (in millions of tonnes) in six different countries over a twenty-year period.",
    band: "9", words: 165,
    text: "The chart compares the amounts of waste that were produced in six countries in the years 1980, 1990 and 2000.\n\nIn each of these years, the US produced more waste than Ireland, Japan, Korea, Poland and Portugal combined. It is also noticeable that Korea was the only country that managed to reduce its waste output by the year 2000.\n\nBetween 1980 and 2000, waste production in the US rose from 131 to 192 million tonnes, and rising trends were also seen in Japan, Poland and Portugal. Japan's waste output increased from 28 to 53 million tonnes, while Poland and Portugal saw waste totals increase from 4 to 6.6 and from 2 to 5 million tonnes respectively.\n\nThe trends for Ireland and Korea were noticeably different from those described above. In Ireland, waste production increased more than eightfold, from only 0.6 million tonnes in 1980 to 5 million tonnes in 2000. Korea, by contrast, cut its waste output by 12 million tonnes between 1990 and 2000."
  },
  {
    type: "task1", subtype: "表格",
    title: "The table below shows changes in the numbers of residents cycling to work in different areas of the UK between 2001 and 2011.",
    band: "9", words: 172,
    text: "The table compares the numbers of people who cycled to work in twelve areas of the UK in the years 2001 and 2011.\n\nOverall, the number of UK commuters who travelled to work by bicycle rose considerably over the 10-year period. Inner London had by far the highest number of cycling commuters in both years.\n\nIn 2001, well over 43 thousand residents of inner London commuted by bicycle, and this figure rose to more than 106 thousand in 2011, an increase of 144%. By contrast, although outer London had the second highest number of cycling commuters in each year, the percentage change, at only 45%, was the lowest of the twelve areas shown in the table.\n\nBrighton and Hove saw the second biggest increase (109%) in the number of residents cycling to work, but Bristol was the UK's second city in terms of total numbers of cycling commuters, with 8,108 in 2001 and 15,768 in 2011. Figures for the other eight areas were below the 10 thousand mark in both years."
  },
  {
    type: "task1", subtype: "流程图",
    title: "The diagram below shows how solar panels can be used to provide electricity for domestic use.",
    band: "9", words: 166,
    tip: "注意文中两类语言特征：表示步骤的语言（steps 词汇）和被动语态，这两点让流程图描述与众不同。",
    text: "The picture illustrates the process of producing electricity in a home using solar panels.\n\nIt is clear that there are five distinct stages in this process, beginning with the capture of energy from sunlight. The final two steps show how domestic electricity is connected to the external power supply.\n\nAt the first stage in the process, solar panels on the roof of a normal house take energy from the sun and convert it into DC current. Next, this current is passed to an inverter, which changes it to AC current and regulates the supply of electricity. At stage three, electricity is supplied to the home from an electrical panel.\n\nAt the fourth step shown on the diagram, a utility meter in the home is responsible for sending any extra electric power outside the house into the grid. Finally, if the solar panels do not provide enough energy for the household, electricity will flow from the utility grid into the home through the meter."
  },
  {
    type: "task1", subtype: "柱状图",
    title: "The bar graph shows the global sales (in billions of dollars) of different types of digital games between 2000 and 2006.",
    band: "9", words: 187,
    text: "The bar chart compares the turnover in dollars from sales of video games for four different platforms, namely mobile phones, online, consoles and handheld devices, from 2000 to 2006.\n\nIt is clear that sales of games for three out of the four platforms rose each year, leading to a significant rise in total global turnover over the 7-year period. Sales figures for handheld games were at least twice as high as those for any other platform in almost every year.\n\nIn 2000, worldwide sales of handheld games stood at around $11 billion, while console games earned just under $6 billion. No figures are given for mobile or online games in that year. Over the next 3 years, sales of handheld video games rose by about $4 billion, but the figure for consoles decreased by $2 billion. Mobile phone and online games started to become popular, with sales reaching around $3 billion in 2003.\n\nIn 2006, sales of handheld, online and mobile games reached peaks of 17, 9 and 7 billion dollars respectively. By contrast, turnover from console games dropped to its lowest point, at around $2.5 billion."
  },
  {
    type: "task1", subtype: "流程图",
    title: "The chart below shows the process of waste paper recycling.",
    band: "9", words: 160,
    text: "The flow chart shows how waste paper is recycled. It is clear that there are six distinct stages in this process, from the initial collection of waste paper to the eventual production of usable paper.\n\nAt the first stage in the paper recycling process, waste paper is collected either from paper banks, where members of the public leave their used paper, or directly from businesses. This paper is then sorted by hand and separated according to its grade, with any paper that is not suitable for recycling being removed. Next, the graded paper is transported to a paper mill.\n\nStages four and five of the process both involve cleaning. The paper is cleaned and pulped, and foreign objects such as staples are taken out. Following this, all remnants of ink and glue are removed from the paper at the de-inking stage. Finally, the pulp can be processed in a paper making machine, which makes the end product: usable paper."
  },
  {
    type: "task1", subtype: "堆叠柱状图",
    title: "The chart below shows the total number of Olympic medals won by twelve different countries.",
    band: "9", words: 178,
    text: "The bar chart compares twelve countries in terms of the overall number of medals that they have won at the Olympic Games.\n\nIt is clear that the USA is by far the most successful Olympic medal winning nation. It is also noticeable that the figures for gold, silver and bronze medals won by any particular country tend to be fairly similar.\n\nThe USA has won a total of around 2,300 Olympic medals, including approximately 900 gold medals, 750 silver and 650 bronze. In second place on the all-time medals chart is the Soviet Union, with just over 1,000 medals. Again, the number of gold medals won by this country is slightly higher than the number of silver or bronze medals.\n\nOnly four other countries - the UK, France, Germany and Italy - have won more than 500 Olympic medals, all with similar proportions of each medal colour. Apart from the USA and the Soviet Union, China is the only other country with a noticeably higher proportion of gold medals (about 200) compared to silver and bronze (about 100 each)."
  },
  {
    type: "task1", subtype: "表格",
    title: "Mobile phone usage in the UK: percentage of people using different functions, 2006-2010.",
    band: "9", words: 178,
    tip: "这篇作文并不完美，但足够达到 band 9。考官不期待你在 20 分钟内写出杰作。",
    text: "The table compares the percentages of people using different functions of their mobile phones between 2006 and 2010.\n\nThroughout the period shown, the main reason why people used their mobile phones was to make calls. However, there was a marked increase in the popularity of other mobile phone features, particularly the Internet search feature.\n\nIn 2006, 100% of mobile phone owners used their phones to make calls, while the next most popular functions were text messaging (73%) and taking photos (66%). By contrast, less than 20% of owners played games or music on their phones, and there were no figures for users doing Internet searches or recording video.\n\nOver the following 4 years, there was relatively little change in the figures for the top three mobile phone features. However, the percentage of people using their phones to access the Internet jumped to 41% in 2008 and then to 73% in 2010. There was also a significant rise in the use of mobiles to play games and to record video, with figures reaching 41% and 35% respectively in 2010."
  },
  {
    type: "task1", subtype: "线形图",
    title: "Average yearly spending by Americans on mobile and landline phone services, 2001-2010.",
    band: "9", words: 162,
    text: "The line graph compares average yearly spending by Americans on mobile and landline phone services from 2001 to 2010.\n\nIt is clear that spending on landline phones fell steadily over the 10-year period, while mobile phone expenditure rose quickly. The year 2006 marks the point at which expenditure on mobile services overtook that for residential phone services.\n\nIn 2001, US consumers spent an average of nearly $700 on residential phone services, compared to only around $200 on cell phone services. Over the following five years, average yearly spending on landlines dropped by nearly $200. By contrast, expenditure on mobiles rose by approximately $300.\n\nIn the year 2006, the average American paid out the same amount of money on both types of phone service, spending just over $500 on each. By 2010, expenditure on mobile phones had reached around $750, while the figure for spending on residential services had fallen to just over half this amount."
  },
  {
    type: "task1", subtype: "组合图",
    title: "The climograph below shows average monthly temperatures and rainfall in the city of Kolkata.",
    band: "9", words: 173,
    text: "The chart compares average figures for temperature and precipitation over the course of a calendar year in Kolkata.\n\nIt is noticeable that monthly figures for precipitation in Kolkata vary considerably, whereas monthly temperatures remain relatively stable. Rainfall is highest from July to August, while temperatures are highest in April and May.\n\nBetween the months of January and May, average temperatures in Kolkata rise from their lowest point at around 20°C to a peak of just over 30°C. Average rainfall in the city also rises over the same period, from approximately 20mm of rain in January to 100mm in May.\n\nWhile temperatures stay roughly the same for the next four months, the amount of rainfall more than doubles between May and June. Figures for precipitation remain above 250mm from June to September, peaking at around 330mm in July. The final three months of the year see a dramatic fall in precipitation, to a low of about 10mm in December, and a steady drop in temperatures back to the January average."
  },
  {
    type: "task1", subtype: "双柱状图",
    title: "Students of different ages: reasons for studying and employer support.",
    band: "9", words: 178,
    text: "The bar charts compare students of different ages in terms of why they are studying and whether they are supported by an employer.\n\nIt is clear that the proportion of students who study for career purposes is far higher among the younger age groups, while the oldest students are more likely to study for interest. Employer support is more commonly given to younger students.\n\nAround 80% of students aged under 26 study to further their careers, whereas only 10% study purely out of interest. The gap between these two proportions narrows as students get older, and the figures for those in their forties are the same, at about 40%. Students aged over 49 overwhelmingly study for interest (70%) rather than for professional reasons (less than 20%).\n\nJust over 60% of students aged under 26 are supported by their employers. By contrast, the 30-39 age group is the most self-sufficient, with only 30% being given time off and help with fees. The figures rise slightly for students in their forties and for those aged 50 or more."
  },
  {
    type: "task1", subtype: "柱状图",
    title: "The chart below shows numbers of incidents and injuries per 100 million passenger miles travelled (PMT) by transportation type in 2002.",
    band: "9", words: 165,
    text: "The bar chart compares the number of incidents and injuries for every 100 million passenger miles travelled on five different types of public transport in 2002.\n\nIt is clear that the most incidents and injuries took place on demand-response vehicles. By contrast, commuter rail services recorded by far the lowest figures.\n\nA total of 225 incidents and 173 injuries, per 100 million passenger miles travelled, took place on demand-response transport services. These figures were nearly three times as high as those for the second highest category, bus services. There were 76 incidents and 66 people were injured on buses.\n\nRail services experienced fewer problems. The number of incidents on light rail trains equalled the figure recorded for buses, but there were significantly fewer injuries, at only 39. Heavy rail services saw lower numbers of such events than light rail services, but commuter rail passengers were even less likely to experience problems. In fact, only 20 incidents and 17 injuries occurred on commuter trains."
  },
  {
    type: "task1", subtype: "线形图",
    title: "The graph below shows the proportion of the population aged 65 and over between 1940 and 2040 in three different countries.",
    band: "9", words: 178,
    text: "The line graph compares the percentage of people aged 65 or more in three countries over a period of 100 years.\n\nIt is clear that the proportion of elderly people increases in each country between 1940 and 2040. Japan is expected to see the most dramatic changes in its elderly population.\n\nIn 1940, around 9% of Americans were aged 65 or over, compared to about 7% of Swedish people and 5% of Japanese people. The proportions of elderly people in the USA and Sweden rose gradually over the next 50 years, reaching just under 15% in 1990. By contrast, the figures for Japan remained below 5% until the early 2000s.\n\nLooking into the future, a sudden increase in the percentage of elderly people is predicted for Japan, with a jump of over 15% in just 10 years from 2030 to 2040. By 2040, it is thought that around 27% of the Japanese population will be 65 years old or more, while the figures for Sweden and the USA will be slightly lower, at about 25% and 23% respectively."
  },
  {
    type: "task1", subtype: "表格",
    title: "The table below gives information on consumer spending on different items in five different countries in 2002. (Percentage of national consumer expenditure by category)",
    band: "9", words: 155,
    text: "The table shows percentages of consumer expenditure for three categories of products and services in five countries in 2002.\n\nIt is clear that the largest proportion of consumer spending in each country went on food, drinks and tobacco. On the other hand, the leisure/education category has the lowest percentages in the table.\n\nOut of the five countries, consumer spending on food, drinks and tobacco was noticeably higher in Turkey, at 32.14%, and Ireland, at nearly 29%. The proportion of spending on leisure and education was also highest in Turkey, at 4.35%, while expenditure on clothing and footwear was significantly higher in Italy, at 9%, than in any of the other countries.\n\nIt can be seen that Sweden had the lowest percentages of national consumer expenditure for food/drinks/tobacco and for clothing/footwear, at nearly 16% and just over 5% respectively. Spain had slightly higher figures for these categories, but the lowest figure for leisure/education, at only 1.98%."
  },
  {
    type: "task1", subtype: "组合图",
    title: "The graph and table below give information about water use worldwide and water consumption in two different countries.",
    band: "9", words: 184,
    text: "The charts compare the amount of water used for agriculture, industry and homes around the world, and water use in Brazil and the Democratic Republic of Congo.\n\nIt is clear that global water needs rose significantly between 1900 and 2000, and that agriculture accounted for the largest proportion of water used. We can also see that water consumption was considerably higher in Brazil than in the Congo.\n\nIn 1900, around 500km³ of water was used by the agriculture sector worldwide. The figures for industrial and domestic water consumption stood at around one fifth of that amount. By 2000, global water use for agriculture had increased to around 3000km³, industrial water use had risen to just under half that amount, and domestic consumption had reached approximately 500km³.\n\nIn the year 2000, the populations of Brazil and the Congo were 176 million and 5.2 million respectively. Water consumption per person in Brazil, at 359m³, was much higher than that in the Congo, at only 8m³, and this could be explained by the fact that Brazil had 265 times more irrigated land."
  },
  {
    type: "task1", subtype: "柱状图",
    title: "The chart below shows information about changes in average house prices in five different cities between 1990 and 2002 compared with the average house prices in 1989.",
    band: "9", words: 165,
    text: "The bar chart compares the cost of an average house in five major cities over a period of 13 years from 1989.\n\nWe can see that house prices fell overall between 1990 and 1995, but most of the cities saw rising prices between 1996 and 2002. London experienced by far the greatest changes in house prices over the 13-year period.\n\nOver the 5 years after 1989, the cost of average homes in Tokyo and London dropped by around 7%, while New York house prices went down by 5%. By contrast, prices rose by approximately 2% in both Madrid and Frankfurt.\n\nBetween 1996 and 2002, London house prices jumped to around 12% above the 1989 average. Homebuyers in New York also had to pay significantly more, with prices rising to 5% above the 1989 average, but homes in Tokyo remained cheaper than they were in 1989. The cost of an average home in Madrid rose by a further 2%, while prices in Frankfurt remained stable."
  },
  {
    type: "task1", subtype: "表格",
    title: "The table below shows the proportion of different categories of families living in poverty in Australia in 1999.",
    band: "9", words: 150,
    text: "The table gives information about poverty rates among six types of household in Australia in the year 1999.\n\nIt is noticeable that levels of poverty were higher for single people than for couples, and people with children were more likely to be poor than those without. Poverty rates were considerably lower among elderly people.\n\nOverall, 11% of Australians, or 1,837,000 people, were living in poverty in 1999. Aged people were the least likely to be poor, with poverty levels of 6% and 4% for single aged people and aged couples respectively.\n\nJust over one fifth of single parents were living in poverty, whereas only 12% of parents living with a partner were classed as poor. The same pattern can be seen for people with no children: while 19% of single people in this group were living below the poverty line, the figure for couples was much lower, at only 7%."
  },
  {
    type: "task1", subtype: "地图题",
    title: "The map below is of the town of Garlsdon. A new supermarket (S) is planned for the town. The map shows two possible sites for the supermarket.",
    band: "9", words: 171,
    text: "The map shows two potential locations (S1 and S2) for a new supermarket in a town called Garlsdon.\n\nThe main difference between the two sites is that S1 is outside the town, whereas S2 is in the town centre. The sites can also be compared in terms of access by road or rail, and their positions relative to three smaller towns.\n\nLooking at the information in more detail, S1 is in the countryside to the north west of Garlsdon, but it is close to the residential area of the town. S2 is also close to the housing area, which surrounds the town centre.\n\nThere are main roads from Hindon, Bransdon and Cransdon to Garlsdon town centre, but this is a no traffic zone, so there would be no access to S2 by car. By contrast, S1 lies on the main road to Hindon, but it would be more difficult to reach from Bransdon and Cransdon. Both supermarket sites are close to the railway that runs through Garlsdon from Hindon to Cransdon."
  },
  {
    type: "task1", subtype: "柱状图",
    title: "Consumer spending on six different items in Germany, Italy, France and Britain.",
    band: "9", words: 150,
    text: "The bar chart compares consumer spending on six different items in Germany, Italy, France and Britain.\n\nIt is clear that British people spent significantly more money than people in the other three countries on all six goods. Of the six items, consumers spent the most money on photographic film.\n\nPeople in Britain spent just over £170,000 on photographic film, which is the highest figure shown on the chart. By contrast, Germans were the lowest overall spenders, with roughly the same figures (just under £150,000) for each of the six products.\n\nThe figures for spending on toys were the same in both France and Italy, at nearly £160,000. However, while French people spent more than Italians on photographic film and CDs, Italians paid out more for personal stereos, tennis racquets and perfumes. The amount spent by French people on tennis racquets, around £145,000, is the lowest figure shown on the chart."
  },
  {
    type: "task1", subtype: "表格",
    title: "The table below gives information about the underground railway systems in six cities.",
    band: "9", words: 185,
    text: "The table shows data about the underground rail networks in six major cities.\n\nThe table compares the six networks in terms of their age, size and the number of people who use them each year. It is clear that the three oldest underground systems are larger and serve significantly more passengers than the newer systems.\n\nThe London underground is the oldest system, having opened in 1863. It is also the largest system, with 394 kilometres of route. The second largest system, in Paris, is only about half the size of the London underground, with 199 kilometres of route. However, it serves more people per year. While only third in terms of size, the Tokyo system is easily the most used, with 1927 million passengers per year.\n\nOf the three newer networks, the Washington DC underground is the most extensive, with 126 kilometres of route, compared to only 11 kilometres and 28 kilometres for the Kyoto and Los Angeles systems. The Los Angeles network is the newest, having opened in 2001, while the Kyoto network is the smallest and serves only 45 million passengers per year."
  },
  {
    type: "task1", subtype: "组合图",
    title: "The chart gives information about UK immigration, emigration and net migration between 1999 and 2008.",
    band: "9", words: 159,
    text: "The chart gives information about UK immigration, emigration and net migration between 1999 and 2008.\n\nBoth immigration and emigration rates rose over the period shown, but the figures for immigration were significantly higher. Net migration peaked in 2004 and 2007.\n\nIn 1999, over 450,000 people came to live in the UK, while the number of people who emigrated stood at just under 300,000. The figure for net migration was around 160,000, and it remained at a similar level until 2003. From 1999 to 2004, the immigration rate rose by nearly 150,000 people, but there was a much smaller rise in emigration. Net migration peaked at almost 250,000 people in 2004.\n\nAfter 2004, the rate of immigration remained high, but the number of people emigrating fluctuated. Emigration fell suddenly in 2007, before peaking at about 420,000 people in 2008. As a result, the net migration figure rose to around 240,000 in 2007, but fell back to around 160,000 in 2008."
  },
  {
    type: "task1", subtype: "三柱状图",
    title: "The charts below show the levels of participation in education and science in developing and industrialised countries in 1980 and 1990.",
    band: "9", words: 187,
    text: "The three bar charts show average years of schooling, numbers of scientists and technicians, and research and development spending in developing and developed countries. Figures are given for 1980 and 1990.\n\nIt is clear from the charts that the figures for developed countries are much higher than those for developing nations. Also, the charts show an overall increase in participation in education and science from 1980 to 1990.\n\nPeople in developing nations attended school for an average of around 3 years, with only a slight increase in years of schooling from 1980 to 1990. On the other hand, the figure for industrialised countries rose from nearly 9 years of schooling in 1980 to nearly 11 years in 1990.\n\nFrom 1980 to 1990, the number of scientists and technicians in industrialised countries almost doubled to about 70 per 1000 people. Spending on research and development also saw rapid growth in these countries, reaching $350 billion in 1990. By contrast, the number of science workers in developing countries remained below 20 per 1000 people, and research spending fell from about $50 billion to only $25 billion."
  },
  {
    type: "task1", subtype: "流程图",
    title: "The figure illustrates the process used by the Australian Bureau of Meteorology to forecast the weather.",
    band: "9", words: 170,
    text: "The figure illustrates the process used by the Australian Bureau of Meteorology to forecast the weather. There are four stages in the process, beginning with the collection of information about the weather. This information is then analysed, prepared for presentation, and finally broadcast to the public.\n\nLooking at the first and second stages of the process, there are three ways of collecting weather data and three ways of analysing it. Firstly, incoming information can be received by satellite and presented for analysis as a satellite photo. The same data can also be passed to a radar station and presented on a radar screen or synoptic chart. Secondly, incoming information may be collected directly by radar and analysed on a radar screen or synoptic chart. Finally, drifting buoys also receive data which can be shown on a synoptic chart.\n\nAt the third stage of the process, the weather broadcast is prepared on computers. Finally, it is delivered to the public on television, on the radio, or as a recorded telephone announcement."
  },
  {
    type: "task1", subtype: "线形图",
    title: "The line graph compares the percentage of people in three countries who used the Internet between 1999 and 2009.",
    band: "9", words: 151,
    text: "The line graph compares the percentage of people in three countries who used the Internet between 1999 and 2009.\n\nIt is clear that the proportion of the population who used the Internet increased in each country over the period shown. Overall, a much larger percentage of Canadians and Americans had access to the Internet in comparison with Mexicans, and Canada experienced the fastest growth in Internet usage.\n\nIn 1999, the proportion of people using the Internet in the USA was about 20%. The figures for Canada and Mexico were lower, at about 10% and 5% respectively. In 2005, Internet usage in both the USA and Canada rose to around 70% of the population, while the figure for Mexico reached just over 25%.\n\nBy 2009, the percentage of Internet users was highest in Canada. Almost 100% of Canadians used the Internet, compared to about 80% of Americans and only 40% of Mexicans."
  }
];
